apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  template:
    spec:
      containers:
      - name: guestbook-ui
        env:
          - name: my-env
            value: my-val